# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HKD' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for HKD
  use_frameworks!
  
pod 'Eureka', '~> 4.0'
pod 'ImageRow', '~> 3.0'
pod 'Charts'
pod 'Alamofire', '~> 4.0.0'
pod 'SwiftyJSON'
pod 'NotificationBannerSwift'
pod 'MKProgress', :git => 'https://github.com/kamirana4/MKProgress.git'
pod 'PayPal.Checkout'
pod 'JWTDecode'
end
